name: Gerar Links Shopee

on:
  workflow_dispatch:

jobs:
  gerar:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - run: pip install requests

    - run: python converter.py

    - name: Salvar resultado
      run: |
        git config --global user.name "bot"
        git config --global user.email "bot@github.com"
        git add resultado.txt
        git commit -m "Gerar links"
        git push
