- name: Commit resultado
  run: |
    git config --global user.name "bot"
    git config --global user.email "bot@github.com"
    git add resultado.txt
    git commit -m "Gerado"
    git push
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
