name: Gerar Links Shopee

on:
  workflow_dispatch:

jobs:
  gerar:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - run: pip install requests

    - run: python gerar.py

   - name: Commit resultado
  run: |
    git config --global user.name "bot"
    git config --global user.email "bot@github.com"

    git add resultado.txt

    git commit -m "Gerado" || echo "Nada para salvar"

    git push || echo "Nada para enviar"
